www_6@Adam MINGW64 /d/software_data/autoQA/API_AutoFramework (master) $ git commit Aborting commit due to empty commit message.
www_6@Adam MINGW64 /d/software_data/autoQA/API_AutoFramework (master)
$ git init
Reinitialized existing Git repository in D:/software_data/autoQA/API_AutoFramework/.git/

www_6@Adam MINGW64 /d/software_data/autoQA/API_AutoFramework (master)
$ git add .
error: open(src/main/resources/excelData/~.xlsx): Permission denied
error: unable to index file 'src/main/resources/excelData/~.xlsx'
fatal: adding files failed

www_6@Adam MINGW64 /d/software_data/autoQA/API_AutoFramework (master)
$ git commit -m